name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get PR diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt
      
      - name: Review with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          DIFF_CONTENT=$(cat pr_diff.txt | jq -Rs .)
          
          RESPONSE=$(curl -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "contents": [{
                "parts": [{
                  "text": "You are an expert code reviewer. Review this pull request and provide constructive feedback. Focus on:\n- Code quality and best practices\n- Potential bugs or issues\n- Security concerns\n- Performance improvements\n- Readability and maintainability\n\nPull Request Diff:\n```diff\n'"$(cat pr_diff.txt)"'\n```\n\nProvide specific, actionable suggestions."
                }]
              }],
              "generationConfig": {
                "temperature": 0.3,
                "maxOutputTokens": 2048
              }
            }')
          
          REVIEW=$(echo $RESPONSE | jq -r '.candidates[0].content.parts[0].text')
          echo "REVIEW<<EOF" >> $GITHUB_ENV
          echo "$REVIEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Post review comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 Gemini AI Code Review\n\n${process.env.REVIEW}`
            })
